service:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: cda.medcom.dk
        paths:
          - path: /
    tls:
      - hosts:
          - cda.medcom.dk
        secretName: cda.medcom.dk

  certificate:
    cda.medcomtools.medcom.dk:
      namespace: medcomtools
      spec:
        secretName: cda.medcom.dk
        issuerRef:
          name: letsencrypt-prod
          kind: ClusterIssuer
          group: cert-manager.io
        dnsNames:
          - cda.medcom.dk
