service:
  fullnameOverride: cdavalidator-schematron-pdc
  namespace: medcomtools
  replicaCount: 1

  ingress:
    enabled: false

  initContainers:
    schematron-resources-builder:
      image:
        repository: "kvalitetsit/medcom-cda-validator-schematron-resources"
        tag: "1.2.0"

      commands:
          - ash
          - -c
          - "cp -R /schematron/art-decor/* /output"

      extraVolumeMounts:
        schematron-resources-dir:
          mountPath: /output

  image:
    repository: goimplementit/cda-validator-schematron
    tag: "1.2.0"

  imagePullSecrets:
    - name: kit4medcom

  serviceAccount:
    create: false

  resources:
    limits:
      memory: "4096Mi"
    requests:
      memory: "512Mi"

  deployment:
    containerPort: 8080
    env: 
      JAVA_OPTS:
        value: "-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m"
      profiles:
        value: "file:/resources/medcom-documents-PDC_s_r.xslt"

    extraVolumes:
      schematron-resources-dir: |
        emptyDir: {}
    extraVolumeMounts:
      schematron-resources-dir:
        mountPath: /resources

  service:
    port: 8080
    targetPort: container-port
