argoApps:
  server: https://kubernetes.default.svc
  repoUrl: git@github.com:KvalitetsIT/medcom-tools-k8s.git

  namespace: medcomtools
  project: medcomtools

  projects:
    medcomtools:
      description: MedCom Tools
      sources:
        - git@github.com:KvalitetsIT/medcom-tools-k8s.git
      destinations:
        - namespace: medcomtools
          server: https://kubernetes.default.svc
        - namespace: argo
          server: https://kubernetes.default.svc          
      ignored:
        - Secret
        - Role
        - RoleBinding
        - AppProject
        - Application
      warnignored: true

  applications:
    redistools:
      path: redis
      targetRevision: main
      valueFiles:
        - values.yaml
